on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Generate Changelog
        id: changelog
        run: |
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          CURRENT_TAG=${GITHUB_REF#refs/tags/}

          if [ -z "$PREVIOUS_TAG" ]; then
            echo "No previous tag found, using all commits"
            COMMITS=$(git log --pretty=format:"%h: %s%n%b" | sed '/^$/d')
            DIFF_SECTION=""
          else
            echo "Previous tag: $PREVIOUS_TAG"
            echo "Current tag: $CURRENT_TAG"
            COMMITS=$(git log --pretty=format:"%h: %s%n%b" $PREVIOUS_TAG..HEAD | sed '/^$/d')
            DIFF_SECTION="## Compare all changes:"$'\n'"[Compare $PREVIOUS_TAG...$CURRENT_TAG](https://github.com/${{ github.repository }}/compare/$PREVIOUS_TAG...$CURRENT_TAG)"$'\n'
          fi

          ADDED=""
          CHANGED=""

          while IFS= read -r line; do
            if [[ $line == *"add:"* ]]; then
              ITEM=$(echo "$line" | sed 's/.*add: //')
              ADDED="$ADDED- $ITEM"$'\n'
            elif [[ $line == *"chg:"* ]]; then
              ITEM=$(echo "$line" | sed 's/.*chg: //')
              CHANGED="$CHANGED- $ITEM"$'\n'
            fi
          done <<< "$COMMITS"

          ADDED=$(echo "$ADDED" | sed '/^$/d')
          CHANGED=$(echo "$CHANGED" | sed '/^$/d')

          ADDED_SECTION=""
          CHANGED_SECTION=""

          if [ -n "$ADDED" ]; then
            ADDED_SECTION="## Added:"$'\n'"$ADDED"$'\n'
          fi

          if [ -n "$CHANGED" ]; then
            CHANGED_SECTION="## Changes:"$'\n'"$CHANGED"$'\n'
          fi

          echo "ADDED_SECTION<<EOF" >> $GITHUB_OUTPUT
          echo "$ADDED_SECTION" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          echo "CHANGED_SECTION<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_SECTION" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          echo "DIFF_SECTION<<EOF" >> $GITHUB_OUTPUT
          echo "$DIFF_SECTION" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: "zip"
          filename: "smartphone.zip"
          path: "./smartphone/"

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "smartphone.zip"
          tag: ${{ github.ref }}
          name: "Smartphone ${{ github.ref_name }}"
          makeLatest: true
          body: |
            <p align="center"><img src="https://github.com/C1XTZ/ac-smartphone/blob/main/.github/img/repopreview.png" width="700"/></p>

            ${{ steps.changelog.outputs.ADDED_SECTION }}${{ steps.changelog.outputs.CHANGED_SECTION }}${{ steps.changelog.outputs.DIFF_SECTION }}

            ## Updating & Installation:
            ### Oldest Supported CSP Version: CSP 0.2.3 (3044)
            ### Updating Ingame:
              ![](https://raw.githubusercontent.com/C1XTZ/ac-smartphone/master/.github/img/updater.png)
            1. Open the Smartphone Ingame
            2. Select the `Update` Tab
            3. Click the `Check for Update` button
            4. Click the `Install Update` button

            ### Automatic Installation via Content Manager: 
            1. Download `smartphone.zip`
            2. Drag & Drop `smartphone.zip` into Content Manager and click `Install`

            ### Manual Installation: 
            1. Download `smartphone.zip`
            2. Extract and place the `smartphone` folder inside the `\apps\lua` folder of your Assetto Corsa installation.
            (By default: `C:\Steam\steamapps\common\assettocorsa\apps\lua`)

            ## Known Issues:
            - Username colors might be incorrect on servers that use custom name color scripts for players that reconnect in a different carslot.
            - Song Information will sometimes be picked up from the wrong source (e.g. Browser instead of Spotify), or not at all.  
              Make sure that `Show desktop overlay when using media keys` is enabled in your Spotify settings or try adding unwanted programs to the `Ignored processes` in the your CSP Music module settings.
