on:
  push:
    tags:
      - 'v*'  

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'smartphone.zip'
        path: './smartphone/'

    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "smartphone.zip"
        tag: ${{ github.ref }}
        name: "Smartphone ${{ github.ref_name }}"
        body: |
          <p align="center"><img src="https://github.com/C1XTZ/ac-smartphone/blob/main/.github/img/repopreview.png" width="700"/></p>
          
          ## Added:

          ## Changes:

          ## Updating & Installation:
          ### Oldest Supported CSP Version: CSP 0.2.3 (3044)
          ### Updating Ingame:
            ![](https://raw.githubusercontent.com/C1XTZ/ac-smartphone/master/.github/img/updater.png)
          1. Open the Smartphone Ingame
          2. Select the `Update` Tab
          3. Click the `Check for Update` button
          4. Click the `Install Update` button

          ### Automatic Installation via Content Manager: 
          1. Download `smartphone.zip`
          2. Drag & Drop `smartphone.zip` into Content Manager and click `Install`

          ### Manual Installation: 
          1. Download `smartphone.zip`
          2. Extract and place the `smartphone` folder inside the `\apps\lua` folder of your Assetto Corsa installation.
          (By default: `C:\Steam\steamapps\common\assettocorsa\apps\lua`)

          ## Known Issues:
          - Username colors might be incorrect on servers that use custom name color scripts for players that reconnect in a different carslot.
          - Song Information will sometimes be picked up from the wrong source (e.g. Browser instead of Spotify), or not at all.  
            Try adding unwanted programs to the `Ignored processes` in the your CSP Music module settings.
          - When using the AssettoServer PatreonTwitchChatPlugin, some Twitch features like Announcements are not be displayed correctly and will result in empty lines

